services:
  db:
    image: timescale/timescaledb:2.17.2-pg16
    environment:
      POSTGRES_DB: rms
      POSTGRES_USER: rms
      POSTGRES_PASSWORD: rms
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rms -d rms"]
      interval: 5s
      timeout: 3s
      retries: 30



  redis:
    image: redis:7-alpine
    command: ["redis-server", "--save", "", "--appendonly", "no"]

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql+psycopg2://rms:rms@db:5432/rms
      JWT_SECRET: rms-super-secret
      DEVICES_CONFIG_PATH: /app/config/devices.json
      REDIS_URL: redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8000:8000"
    volumes:
      - ./collector/config:/app/config:ro

  collector:
    build: ./collector
    environment:
      BACKEND_URL: http://backend:8000
      DEVICES_CONFIG: /app/config/devices.json
      DEVICE_TIMEOUT_SEC: 1.0
    depends_on:
      - backend
    volumes:
      - ./collector/config:/app/config:ro
      - collector_buffer:/app/data

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  db_data:
  collector_buffer:
